### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by andridgitalbox** [brainlabs/surat#1]
Terima kasih atas source nya ...sangat membantu sekali untuk newbie
saya mau tanya kenapa saya coba untuk apps surat nya tidak bisa ?
sudah bener import database nya tapi malah not found http://localhost/surat-master/auth saat jalanin itu..apakah ada yg salah ?terima kasih

**Comment by brainlabs** [comment]
coba perhatikan htaccessnya gan yang RewriteBase /surat ganti jadi RewriteBase /surat-master

**Comment by ontzuevanhussen** [comment]
username sama passwordnya administrator suratnya apa ya waktu mau login pertama? saya ga bisa akses. makasih yaa..
